version: '3'

services:
  auth-service:
    build:
      context: . # Use an image built from the specified Dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}" # Use the PORT variable from the .env file
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MODE=production
      - PORT=${PORT}
