basePath: /
definitions:
  application.ApplicationLoginBody:
    properties:
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
    type: object
  application.ApplicationLoginResponse:
    properties:
      base_secret:
        type: string
    type: object
  application.ApplicationRegisterBody:
    properties:
      description:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - description
    - name
    - password
    type: object
  application.ApplicationRegisterResponse:
    properties:
      base_secret:
        type: string
    type: object
  utils.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  utils.SuccessResponse-application_ApplicationLoginResponse:
    properties:
      data:
        $ref: '#/definitions/application.ApplicationLoginResponse'
      message:
        type: string
      success:
        type: boolean
    type: object
  utils.SuccessResponse-application_ApplicationRegisterResponse:
    properties:
      data:
        $ref: '#/definitions/application.ApplicationRegisterResponse'
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:4444
info:
  contact: {}
  description: This is the API for the Auth Service
  title: Auth Service API
  version: "1.0"
paths:
  /application/login:
    post:
      consumes:
      - application/json
      description: Login an application
      parameters:
      - description: Authorization key
        in: header
        name: Auth-Service-Authorization
        required: true
        type: string
      - description: Application login body
        in: body
        name: application
        required: true
        schema:
          $ref: '#/definitions/application.ApplicationLoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.SuccessResponse-application_ApplicationLoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Login an application
      tags:
      - Application
  /application/register:
    post:
      consumes:
      - application/json
      description: Register an application
      parameters:
      - description: Authorization key
        in: header
        name: Auth-Service-Authorization
        required: true
        type: string
      - description: Application register body
        in: body
        name: application
        required: true
        schema:
          $ref: '#/definitions/application.ApplicationRegisterBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.SuccessResponse-application_ApplicationRegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Register an application
      tags:
      - Application
swagger: "2.0"
