name: Build, Test and Deploy Go App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO_ENV: production
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22.0"

      - name: Install dependencies
        run: go mod tidy

      # - name: Run tests
        # run: go test ./...

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      - name: Deploy to Server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@${{ secrets.SSH_HOST }} << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
            docker stop auth-service || true
            docker rm auth-service || true
            docker run -d --name auth-service -p 80:80 --env-file /path/to/env/file ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
