name: Build, Test and Deploy Express App

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  pull_request:
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.0'

    - name: Install dependencies
      working-directory: server
      run: npm install

    - name: Run tests
      working-directory: server
      run: npm test

    - name: Build app
      working-directory: server
      run: npm run build

    - name: Deploy to Server
      working-directory: server
      run: |
        scp -r . user@yourserver:/path/to/deploy
        ssh user@yourserver 'systemctl restart your-express-app-service'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}